/*******************************************************************************
* File Name: cyfitter_sysint_cfg.h
* 
* PSoC Creator  4.3
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_CFG_H
#define INCLUDED_CYFITTER_SYSINT_CFG_H

#include "sysint/cy_sysint.h"

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))
    #define AllGpio_Int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t AllGpio_Int_cfg;

    #define LPComp_Int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t LPComp_Int_cfg;

    #define I2CM_SCB_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t I2CM_SCB_IRQ_cfg;

    #define SPIM_SCB_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t SPIM_SCB_IRQ_cfg;

    #define I2CS_SCB_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t I2CS_SCB_IRQ_cfg;

    #define SPIS_SCB_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t SPIS_SCB_IRQ_cfg;

    #define UART_SCB_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t UART_SCB_IRQ_cfg;

    #define EZI2C_1_SCB_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t EZI2C_1_SCB_IRQ_cfg;

    #define CapSense_ISR__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t CapSense_ISR_cfg;

    #define Counter_Int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Counter_Int_cfg;

    #define ADC_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t ADC_IRQ_cfg;

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */

/* ARM CM0+ */
#if (((__CORTEX_M == 0) && (CY_CORE_ID == 0)))
    #define UART_SCB_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t UART_SCB_IRQ_cfg;

    #define EZI2C_1_SCB_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t EZI2C_1_SCB_IRQ_cfg;

    #define CapSense_ISR__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t CapSense_ISR_cfg;

#endif /* ((__CORTEX_M == 0) && (CY_CORE_ID == 0)) */


#endif /* INCLUDED_CYFITTER_SYSINT_CFG_H */
