/*******************************************************************************
* File Name: cyfitter_sysint_cfg.c
* 
* PSoC Creator  4.3
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_sysint.h"
#include "cyfitter_sysint_cfg.h"

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))

    /* AllGpio_Int */
    const cy_stc_sysint_t AllGpio_Int_cfg = {
        .intrSrc = (IRQn_Type)AllGpio_Int__INTC_NUMBER,
        .intrPriority = AllGpio_Int__INTC_CORTEXM4_PRIORITY
    };

    /* LPComp_Int */
    const cy_stc_sysint_t LPComp_Int_cfg = {
        .intrSrc = (IRQn_Type)LPComp_Int__INTC_NUMBER,
        .intrPriority = LPComp_Int__INTC_CORTEXM4_PRIORITY
    };

    /* I2CM_SCB_IRQ */
    const cy_stc_sysint_t I2CM_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)I2CM_SCB_IRQ__INTC_NUMBER,
        .intrPriority = I2CM_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* SPIM_SCB_IRQ */
    const cy_stc_sysint_t SPIM_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)SPIM_SCB_IRQ__INTC_NUMBER,
        .intrPriority = SPIM_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* I2CS_SCB_IRQ */
    const cy_stc_sysint_t I2CS_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)I2CS_SCB_IRQ__INTC_NUMBER,
        .intrPriority = I2CS_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* SPIS_SCB_IRQ */
    const cy_stc_sysint_t SPIS_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)SPIS_SCB_IRQ__INTC_NUMBER,
        .intrPriority = SPIS_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* UART_SCB_IRQ */
    const cy_stc_sysint_t UART_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)UART_SCB_IRQ__INTC_NUMBER,
        .intrPriority = UART_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* EZI2C_1_SCB_IRQ */
    const cy_stc_sysint_t EZI2C_1_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)EZI2C_1_SCB_IRQ__INTC_NUMBER,
        .intrPriority = EZI2C_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* CapSense_ISR */
    const cy_stc_sysint_t CapSense_ISR_cfg = {
        .intrSrc = (IRQn_Type)CapSense_ISR__INTC_NUMBER,
        .intrPriority = CapSense_ISR__INTC_CORTEXM4_PRIORITY
    };

    /* Counter_Int */
    const cy_stc_sysint_t Counter_Int_cfg = {
        .intrSrc = (IRQn_Type)Counter_Int__INTC_NUMBER,
        .intrPriority = Counter_Int__INTC_CORTEXM4_PRIORITY
    };

    /* ADC_IRQ */
    const cy_stc_sysint_t ADC_IRQ_cfg = {
        .intrSrc = (IRQn_Type)ADC_IRQ__INTC_NUMBER,
        .intrPriority = ADC_IRQ__INTC_CORTEXM4_PRIORITY
    };

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */

/* ARM CM0+ */
#if (((__CORTEX_M == 0) && (CY_CORE_ID == 0)))

    /* UART_SCB_IRQ */
    const cy_stc_sysint_t UART_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)UART_SCB_IRQ__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)UART_SCB_IRQ__INTC_NUMBER,
        .intrPriority = UART_SCB_IRQ__INTC_CORTEXM0P_PRIORITY
    };

    /* EZI2C_1_SCB_IRQ */
    const cy_stc_sysint_t EZI2C_1_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)EZI2C_1_SCB_IRQ__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)EZI2C_1_SCB_IRQ__INTC_NUMBER,
        .intrPriority = EZI2C_1_SCB_IRQ__INTC_CORTEXM0P_PRIORITY
    };

    /* CapSense_ISR */
    const cy_stc_sysint_t CapSense_ISR_cfg = {
        .intrSrc = (IRQn_Type)CapSense_ISR__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)CapSense_ISR__INTC_NUMBER,
        .intrPriority = CapSense_ISR__INTC_CORTEXM0P_PRIORITY
    };

#endif /* ((__CORTEX_M == 0) && (CY_CORE_ID == 0)) */

